from setuptools import setup

setup(
    name='courage_algorithms',
    version='0.0.1',
    author='Gregor Donabauer',
    author_email='gregor.donabauer@ur.de',
    packages=['courage_algorithms.scripts', 'courage_algorithms.DE_text_algorithms',
              'courage_algorithms.EN_text_algorithms', 'courage_algorithms.ES_text_algorithms',
              'courage_algorithms.IT_text_algorithms', 'courage_algorithms.image_algorithms'],
    scripts=[],
    url='https://github.com/doGregor/COURAGE_api',
    license='',
    description='Collection of algorithms to analyze social media content in the COURAGE project',
    long_description='',
    install_requires=[
        "click==8.0.4",
        "colorama==0.4.4",
        "flair==0.11.1",
        "Flask==2.0.2",
        "itsdangerous==2.0.1",
        "Jinja2==3.0.2",
        "keras==2.8.0",
        "MarkupSafe==2.0.1",
        "nltk==3.7",
        "numpy==1.21.5",
        "opencv-python~=4.5.5",
        "pandas==1.4.1",
        "Pillow==9.0.1",
        "requests==2.27.1",
        "scikit-learn==1.0.2",
        "scipy==1.8.0",
        "torch==1.11.0",
        "transformers==4.17.0",
        "Werkzeug==2.0.3",
        "pytest",
    ],
)
